name: metabugo
description: "meta_bugo"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  kakao_flutter_sdk: ^1.9.1+2
  date_picker_plus: ^3.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: KoPubBatang
      fonts:
        - asset: assets/font/KoPubBatangLight.ttf
          weight: 300
        - asset: assets/font/KoPubBatangMedium.ttf
          weight: 500
        - asset: assets/font/KoPubBatangBold.ttf
          weight: 700
    - family: pretendard
      fonts:
        - asset: assets/font/pretendardBold.otf
          weight: 700
        - asset: assets/font/pretendardSemiBold.otf
          weight: 600
        - asset: assets/font/pretendardMedium.otf
          weight: 500
        - asset: assets/font/pretendardRegular.otf
          weight: 400

  assets:
    - assets/images/candle.png
    - assets/images/splash_images/splash.png
    - assets/images/kakao.png
    - assets/images/flower_icon.png
